M48
; DRILL file {KiCad (6.0.0)} date Sat Jan 22 21:28:24 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-01-22T21:28:24-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0236
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1378
%
G90
G05
T1
X5.2835Y-3.5488
X5.7165Y-3.5488
T2
X3.7Y-2.1441
T0
M30
